[0m21:06:01.729440 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C11FD8A350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C121CDFB20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C121CDD870>]}


============================== 21:06:01.729440 | f4071f59-e1a2-42c8-b41e-c6ba5517ec7d ==============================
[0m21:06:01.729440 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:06:01.729440 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Temp\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init my_project', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:06:01.781534 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': WindowsPath('C:/Users/Temp/.dbt')}
[0m21:06:01.784534 [info ] [MainThread]: Creating dbt configuration folder at 
[0m21:06:01.786535 [debug] [MainThread]: Starter project path: C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\week7\lib\site-packages\dbt\include\starter_project
[0m21:06:01.864321 [info ] [MainThread]: 
Your new dbt project "my_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:06:01.864321 [info ] [MainThread]: Setting up your profile.
[0m21:07:57.984328 [info ] [MainThread]: Profile my_project written to C:\Users\Temp\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m21:07:57.992776 [debug] [MainThread]: Command `dbt init` succeeded at 21:07:57.991392 after 116.36 seconds
[0m21:07:57.993789 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C11FD8A350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C121B37DF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002C121D1FBE0>]}
[0m21:07:57.994969 [debug] [MainThread]: Flushing usage events
[0m21:07:59.253540 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:12:37.852353 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D07F2EA2F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0012D0D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0012D31C0>]}


============================== 21:12:37.857397 | 082e3962-0458-40ac-81bf-bd9049be0448 ==============================
[0m21:12:37.857397 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:12:37.858299 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Temp\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:12:37.859299 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:12:37.860382 [debug] [MainThread]: Command `dbt run` failed at 21:12:37.860382 after 0.10 seconds
[0m21:12:37.861397 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D07F2EA2F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D0012D02E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D001306E60>]}
[0m21:12:37.861397 [debug] [MainThread]: Flushing usage events
[0m21:12:40.232711 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:13:42.584907 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012F436FA3B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012F45686B00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012F45686CE0>]}


============================== 21:13:42.590000 | fe551b39-2a4e-40c4-b7e6-7a03cae11312 ==============================
[0m21:13:42.590000 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:13:42.590907 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Temp\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m21:13:42.591904 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:13:42.593996 [debug] [MainThread]: Command `dbt run` failed at 21:13:42.593023 after 0.10 seconds
[0m21:13:42.593996 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012F436FA3B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012F45686CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000012F45686A40>]}
[0m21:13:42.595005 [debug] [MainThread]: Flushing usage events
[0m21:13:44.558637 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:14:57.915862 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000295CF3FA440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000295D1386C80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000295D1386E60>]}


============================== 21:14:57.915862 | a9c4a2b0-ec90-46e3-b6bc-948310313c89 ==============================
[0m21:14:57.915862 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:14:57.915862 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Temp\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m21:14:57.915862 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:14:57.915862 [debug] [MainThread]: Command `dbt run` failed at 21:14:57.915862 after 0.09 seconds
[0m21:14:57.915862 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000295CF3FA440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000295D1386E60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000295D1386BC0>]}
[0m21:14:57.915862 [debug] [MainThread]: Flushing usage events
[0m21:14:58.872276 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:17:14.058205 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225AE14A3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B00DE3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B00DE200>]}


============================== 21:17:14.062496 | 3e64e1d1-f1fa-46b6-befc-1e793bee6dd4 ==============================
[0m21:17:14.062496 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:17:14.063832 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\Temp\\Desktop\\KAI-Projects\\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\\logs', 'profiles_dir': 'C:\\Users\\Temp\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:17:14.293531 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '3e64e1d1-f1fa-46b6-befc-1e793bee6dd4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225AD43F100>]}
[0m21:17:14.353765 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '3e64e1d1-f1fa-46b6-befc-1e793bee6dd4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B0023DC0>]}
[0m21:17:14.355652 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m21:17:14.612957 [debug] [MainThread]: checksum: 12b12750b70de726cfd89136b8e24afc3f3e77597a97bff40ab7e5f9b39d5e18, vars: {}, profile: , target: , version: 1.9.2
[0m21:17:14.613956 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m21:17:14.614611 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '3e64e1d1-f1fa-46b6-befc-1e793bee6dd4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225AD454E80>]}
[0m21:17:16.856949 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_project.example
[0m21:17:16.862613 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '3e64e1d1-f1fa-46b6-befc-1e793bee6dd4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225AFF35180>]}
[0m21:17:16.914016 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\manifest.json
[0m21:17:16.942622 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\semantic_manifest.json
[0m21:17:16.981292 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '3e64e1d1-f1fa-46b6-befc-1e793bee6dd4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B0762F80>]}
[0m21:17:16.981292 [info ] [MainThread]: Found 433 macros
[0m21:17:16.983297 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '3e64e1d1-f1fa-46b6-befc-1e793bee6dd4', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B0763A00>]}
[0m21:17:16.984392 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m21:17:16.985322 [debug] [MainThread]: Command end result
[0m21:17:17.006317 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\manifest.json
[0m21:17:17.009294 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\semantic_manifest.json
[0m21:17:17.013325 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\run_results.json
[0m21:17:17.014302 [debug] [MainThread]: Command `dbt run` succeeded at 21:17:17.014302 after 3.04 seconds
[0m21:17:17.015295 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225AE14A3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225B0023DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225AE476350>]}
[0m21:17:17.016296 [debug] [MainThread]: Flushing usage events
[0m21:17:18.113977 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:17:49.798206 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022600BEA410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022602B7E590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022602B7E3B0>]}


============================== 21:17:49.806215 | 900b64f2-abf7-4a42-bcbd-7b04084b969a ==============================
[0m21:17:49.806215 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:17:49.808207 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Users\\Temp\\Desktop\\KAI-Projects\\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\\logs', 'profiles_dir': 'C:\\Users\\Temp\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt test', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m21:17:50.095721 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '900b64f2-abf7-4a42-bcbd-7b04084b969a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002267F440CA0>]}
[0m21:17:50.168846 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '900b64f2-abf7-4a42-bcbd-7b04084b969a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022602B7E650>]}
[0m21:17:50.171308 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m21:17:50.387850 [debug] [MainThread]: checksum: 12b12750b70de726cfd89136b8e24afc3f3e77597a97bff40ab7e5f9b39d5e18, vars: {}, profile: , target: , version: 1.9.2
[0m21:17:50.513897 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m21:17:50.513897 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m21:17:50.514897 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_project.example
[0m21:17:50.522900 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '900b64f2-abf7-4a42-bcbd-7b04084b969a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000226032E2800>]}
[0m21:17:50.593163 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\manifest.json
[0m21:17:50.597818 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\semantic_manifest.json
[0m21:17:50.657525 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '900b64f2-abf7-4a42-bcbd-7b04084b969a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000226032F9720>]}
[0m21:17:50.657525 [info ] [MainThread]: Found 433 macros
[0m21:17:50.659527 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '900b64f2-abf7-4a42-bcbd-7b04084b969a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000226031320E0>]}
[0m21:17:50.660528 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m21:17:50.663527 [debug] [MainThread]: Command end result
[0m21:17:50.692648 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\manifest.json
[0m21:17:50.695532 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\semantic_manifest.json
[0m21:17:50.701161 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\run_results.json
[0m21:17:50.703234 [debug] [MainThread]: Command `dbt test` succeeded at 21:17:50.703234 after 1.07 seconds
[0m21:17:50.704238 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022600BEA410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022602F083D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002267F4BC0A0>]}
[0m21:17:50.705238 [debug] [MainThread]: Flushing usage events
[0m21:17:51.568375 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:18:01.908384 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB1EF4A380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB20ED6AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB20ED6CB0>]}


============================== 21:18:01.913898 | 8a2a1373-6775-4c1b-ba54-904278acb32a ==============================
[0m21:18:01.913898 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:18:01.914896 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'C:\\Users\\Temp\\Desktop\\KAI-Projects\\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\\logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Temp\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:18:02.211907 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '8a2a1373-6775-4c1b-ba54-904278acb32a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB1DFA8C70>]}
[0m21:18:02.283070 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '8a2a1373-6775-4c1b-ba54-904278acb32a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB1F28E2F0>]}
[0m21:18:02.285058 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m21:18:02.521569 [debug] [MainThread]: checksum: 12b12750b70de726cfd89136b8e24afc3f3e77597a97bff40ab7e5f9b39d5e18, vars: {}, profile: , target: , version: 1.9.2
[0m21:18:02.649241 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m21:18:02.650239 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m21:18:02.651242 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.my_project.example
[0m21:18:02.657242 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '8a2a1373-6775-4c1b-ba54-904278acb32a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB21642770>]}
[0m21:18:02.700476 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '8a2a1373-6775-4c1b-ba54-904278acb32a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB21642FE0>]}
[0m21:18:02.702566 [info ] [MainThread]: Found 433 macros
[0m21:18:02.703469 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '8a2a1373-6775-4c1b-ba54-904278acb32a', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB21643F10>]}
[0m21:18:02.705570 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m21:18:02.708571 [debug] [MainThread]: Command end result
[0m21:18:02.767224 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\manifest.json
[0m21:18:02.771184 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\semantic_manifest.json
[0m21:18:02.776181 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\run_results.json
[0m21:18:03.289623 [debug] [MainThread]: Acquiring new postgres connection 'generate_catalog'
[0m21:18:03.289623 [info ] [MainThread]: Building catalog
[0m21:18:06.629103 [debug] [MainThread]: Wrote artifact CatalogArtifact to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\catalog.json
[0m21:18:06.660461 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\manifest.json
[0m21:18:06.660461 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\semantic_manifest.json
[0m21:18:06.660461 [info ] [MainThread]: Catalog written to C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\target\catalog.json
[0m21:18:06.660461 [debug] [MainThread]: Command `dbt docs generate` succeeded at 21:18:06.660461 after 4.84 seconds
[0m21:18:06.660461 [debug] [MainThread]: Connection 'generate_catalog' was properly closed.
[0m21:18:06.660461 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB1EF4A380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB20A13A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB21643820>]}
[0m21:18:06.660461 [debug] [MainThread]: Flushing usage events
[0m21:18:07.763220 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:18:21.347971 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000010EDA5DA3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000010EDC56E440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000010EDC56E260>]}


============================== 21:18:21.355967 | 8ff648f3-d6c5-44fc-9a5e-f1dd8a960414 ==============================
[0m21:18:21.355967 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:18:21.355967 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Temp\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\Users\\Temp\\Desktop\\KAI-Projects\\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\\logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt docs serve', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:18:21.615278 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '8ff648f3-d6c5-44fc-9a5e-f1dd8a960414', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000010EDA8F6A70>]}
[0m21:18:21.679634 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '8ff648f3-d6c5-44fc-9a5e-f1dd8a960414', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000010EDA91B520>]}
[0m21:21:50.633673 [error] [MainThread]: Encountered an error:

[0m21:21:50.682761 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\week7\lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\week7\lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\week7\lib\site-packages\dbt\cli\requires.py", line 235, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\week7\lib\site-packages\dbt\cli\requires.py", line 264, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\week7\lib\site-packages\dbt\cli\requires.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\week7\lib\site-packages\dbt\cli\main.py", line 301, in docs_serve
    results = task.run()
  File "C:\Users\Temp\Desktop\KAI-Projects\Building-Data-Warehouse-to-store-Ethiopian-medical-business-data\week7\lib\site-packages\dbt\task\docs\serve.py", line 29, in run
    httpd.serve_forever()
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\Temp\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
KeyboardInterrupt

[0m21:21:50.699429 [debug] [MainThread]: Command `dbt docs serve` failed at 21:21:50.698436 after 209.45 seconds
[0m21:21:50.699429 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000010EDA5DA3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000010EDC9C2CB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000010EDC9C2FB0>]}
[0m21:21:50.700441 [debug] [MainThread]: Flushing usage events
[0m21:21:50.706427 [debug] [MainThread]: An error was encountered while trying to flush usage events
